In [43]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [44]:
df = pd.DataFrame({'reviews' : [
    "This movie is amazing!",
    "The plot was confusing and the acting was terrible.",
    "I enjoyed the movie. The characters were well-developed.",
    "I didn't like the movie at all. It was boring and predictable."
]})

In [45]:
df

reviews
0                             This movie is amazing!
1  The plot was confusing and the acting was terr...
2  I enjoyed the movie. The characters were well-...
3  I didn't like the movie at all. It was boring ...

In [46]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(ngram_range=(1,1)) #bog of words(default)
cv1 = CountVectorizer(ngram_range=(1,2)) #uni-grams and bi-grams
cv2 = CountVectorizer(ngram_range=(2,2)) #bi-grams
cv3 = CountVectorizer(ngram_range=(3,3)) #tri-grams

In [47]:
x = df['reviews']

x_cv = cv.fit_transform(x)
x_cv1 = cv1.fit_transform(x)
x_cv2 = cv2.fit_transform(x)
x_cv3 = cv3.fit_transform(x)

In [48]:
cv.vocabulary_

{'this': 19,
 'movie': 14,
 'is': 11,
 'amazing': 2,
 'the': 18,
 'plot': 15,
 'was': 20,
 'confusing': 7,
 'and': 3,
 'acting': 0,
 'terrible': 17,
 'enjoyed': 10,
 'characters': 6,
 'were': 22,
 'well': 21,
 'developed': 8,
 'didn': 9,
 'like': 13,
 'at': 4,
 'all': 1,
 'it': 12,
 'boring': 5,
 'predictable': 16}

In [49]:
x_np = x_cv.toarray()
x_np

array([[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
        0],
       [1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 2, 0, 2, 0,
        0],
       [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 1,
        1],
       [0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
        0]])

In [50]:
cv1.vocabulary_

{'this': 40,
 'movie': 27,
 'is': 21,
 'amazing': 4,
 'this movie': 41,
 'movie is': 29,
 'is amazing': 22,
 'the': 35,
 'plot': 31,
 'was': 42,
 'confusing': 14,
 'and': 5,
 'acting': 0,
 'terrible': 34,
 'the plot': 39,
 'plot was': 32,
 'was confusing': 44,
 'confusing and': 15,
 'and the': 7,
 'the acting': 36,
 'acting was': 1,
 'was terrible': 45,
 'enjoyed': 19,
 'characters': 12,
 'were': 48,
 'well': 46,
 'developed': 16,
 'enjoyed the': 20,
 'the movie': 38,
 'movie the': 30,
 'the characters': 37,
 'characters were': 13,
 'were well': 49,
 'well developed': 47,
 'didn': 17,
 'like': 25,
 'at': 8,
 'all': 2,
 'it': 23,
 'boring': 10,
 'predictable': 33,
 'didn like': 18,
 'like the': 26,
 'movie at': 28,
 'at all': 9,
 'all it': 3,
 'it was': 24,
 'was boring': 43,
 'boring and': 11,
 'and predictable': 6}

In [60]:
x_np1 = x_cv1.toarray()
x_np1

array([[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 2, 1, 0, 0, 1, 0, 0, 2, 0,
        1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 2, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1],
       [0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
        0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 0, 0]])

In [51]:
cv2.vocabulary_

{'this movie': 21,
 'movie is': 14,
 'is amazing': 10,
 'the plot': 20,
 'plot was': 16,
 'was confusing': 23,
 'confusing and': 7,
 'and the': 3,
 'the acting': 17,
 'acting was': 0,
 'was terrible': 24,
 'enjoyed the': 9,
 'the movie': 19,
 'movie the': 15,
 'the characters': 18,
 'characters were': 6,
 'were well': 26,
 'well developed': 25,
 'didn like': 8,
 'like the': 12,
 'movie at': 13,
 'at all': 4,
 'all it': 1,
 'it was': 11,
 'was boring': 22,
 'boring and': 5,
 'and predictable': 2}

In [61]:
x_np2 = x_cv2.toarray()
x_np2

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
        0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
        0, 0, 0, 1, 1],
       [0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
        1, 0, 0, 0, 0]])

In [58]:
cv3.vocabulary_

{'this movie is': 20,
 'movie is amazing': 12,
 'the plot was': 19,
 'plot was confusing': 14,
 'was confusing and': 22,
 'confusing and the': 6,
 'and the acting': 2,
 'the acting was': 15,
 'acting was terrible': 0,
 'enjoyed the movie': 8,
 'the movie the': 18,
 'movie the characters': 13,
 'the characters were': 16,
 'characters were well': 5,
 'were well developed': 23,
 'didn like the': 7,
 'like the movie': 10,
 'the movie at': 17,
 'movie at all': 11,
 'at all it': 3,
 'all it was': 1,
 'it was boring': 9,
 'was boring and': 21,
 'boring and predictable': 4}

In [62]:
x_np3 = x_cv3.toarray()
x_np3

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0],
       [1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
        1, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
        0, 1],
       [0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
        0, 0]])

In [56]:
print('{0:25} {1:25} {2:25} {3:25}'.format('Uni-grams','Uni-grams & Bi-grams','Bi-grams','Tri-grams'))
print('{0:25} {1:25} {2:25} {3:25}'.format(str(len(cv.vocabulary_)),str(len(cv1.vocabulary_)),str(len(cv2.vocabulary_)),str(len(cv3.vocabulary_))))

Uni-grams                 Uni-grams & Bi-grams      Bi-grams                  Tri-grams                
23                        50                        27                        24                       
