In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/spam-dataset/spam.csv


In [3]:
df = pd.read_csv('/kaggle/input/spam-dataset/spam.csv')

In [4]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
df['Message'][2]

"Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"

In [7]:
df['Category'].value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [9]:
df['spam'] = df['Category'].apply(lambda x : 1 if x == 'spam' else 0)

In [10]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [17]:
df.shape 

(5572, 3)

## Train and split

In [12]:
from sklearn.model_selection import train_test_split 

In [13]:
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size = 0.2)

In [14]:
type(X_train)

pandas.core.series.Series

In [16]:
X_train[4034]

'I am taking you for italian food. How about a pretty dress with no panties? :)'

In [21]:
print(X_train.shape,X_test.shape)

(4457,) (1115,)


In [70]:
X_train.values

array(['I am taking you for italian food. How about a pretty dress with no panties? :)',
       'WIN: We have a winner! Mr. T. Foley won an iPod! More exciting prizes soon, so keep an eye on ur mobile or visit www.win-82050.co.uk',
       'We are okay. Going to sleep now. Later', ..., 'Okie',
       'Call me when you get the chance plz &lt;3',
       '2 laptop... I noe infra but too slow lar... I wan fast one'],
      dtype=object)

In [24]:
type(X_train.values)

numpy.ndarray

## Create bag of words representation using CountVectorizer

### when you performing a project first use basic-preprocessing to remove stopwords,emojis etc 

In [27]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

In [28]:
X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7819 sparse matrix of type '<class 'numpy.int64'>'
	with 59635 stored elements in Compressed Sparse Row format>

In [29]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'bui

In [63]:
X_train_cv.shape

(4457, 7819)

In [72]:
X_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [44]:
v.get_feature_names_out()[6159]

'ship'

In [67]:
len(v.vocabulary_.keys())

7819

In [49]:
sorted(v.vocabulary_.items(), key = lambda x :x[1],reverse = True)

[('〨ud', 7818),
 ('ú1', 7817),
 ('èn', 7816),
 ('zyada', 7815),
 ('zouk', 7814),
 ('zoom', 7813),
 ('zogtorius', 7812),
 ('zoe', 7811),
 ('zindgi', 7810),
 ('zhong', 7809),
 ('zeros', 7808),
 ('zed', 7807),
 ('zebra', 7806),
 ('zealand', 7805),
 ('zaher', 7804),
 ('zac', 7803),
 ('yupz', 7802),
 ('yup', 7801),
 ('yuou', 7800),
 ('yuo', 7799),
 ('yunny', 7798),
 ('yun', 7797),
 ('yummy', 7796),
 ('yummmm', 7795),
 ('ything', 7794),
 ('ystrday', 7793),
 ('yrs', 7792),
 ('yr', 7791),
 ('yoyyooo', 7790),
 ('yowifes', 7789),
 ('youwanna', 7788),
 ('youuuuu', 7787),
 ('yourself', 7786),
 ('yours', 7785),
 ('yourjob', 7784),
 ('yourinclusive', 7783),
 ('youre', 7782),
 ('your', 7781),
 ('youphone', 7780),
 ('younger', 7779),
 ('young', 7778),
 ('youi', 7777),
 ('youdoing', 7776),
 ('you', 7775),
 ('yorge', 7774),
 ('yor', 7773),
 ('yogasana', 7772),
 ('yoga', 7771),
 ('yo', 7770),
 ('ymca', 7769),
 ('ym', 7768),
 ('yijue', 7767),
 ('yifeng', 7766),
 ('yi', 7765),
 ('yhl', 7764),
 ('yetunde', 

In [41]:
X_train_np = X_train_cv.toarray()

In [62]:
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [57]:
np.where(X_train_np[0] != 0)

(array([ 785,  966, 2501, 3001, 3009, 3589, 3829, 4859, 5124, 5462, 6761,
        7608, 7775]),)

In [76]:
X_train[:4][4034]

'I am taking you for italian food. How about a pretty dress with no panties? :)'

In [84]:
X_train_np[0][6761]

1

In [80]:
v.get_feature_names_out()[2501]

'dress'